In [1]:
# Importing necessary libraries
from sklearn.preprocessing import MinMaxScaler, StandardScaler, MaxAbsScaler
import numpy as np

# Sample dataset
data = np.array([[1, -1, 2],
                 [2, 0, 0],
                 [0, 1, -1]])

# 1. MinMaxScaler
# Scales features to a range, typically [0, 1]
min_max_scaler = MinMaxScaler()
data_minmax = min_max_scaler.fit_transform(data)

print("Original Data:")
print(data)
print("\nMinMax Scaled Data (Range [0, 1]):")
print(data_minmax)


Original Data:
[[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]

MinMax Scaled Data (Range [0, 1]):
[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]


In [2]:
# 2. StandardScaler
# Scales features to have zero mean and unit variance
standard_scaler = StandardScaler()
data_standard = standard_scaler.fit_transform(data)

print("\nStandard Scaled Data (Zero mean, unit variance):")
print(data_standard)



Standard Scaled Data (Zero mean, unit variance):
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [3]:

# 3. MaxAbsScaler
# Scales features to the range [-1, 1] by dividing by the maximum absolute value
max_abs_scaler = MaxAbsScaler()
data_maxabs = max_abs_scaler.fit_transform(data)

print("\nMaxAbs Scaled Data (Range [-1, 1]):")
print(data_maxabs)



MaxAbs Scaled Data (Range [-1, 1]):
[[ 0.5 -1.   1. ]
 [ 1.   0.   0. ]
 [ 0.   1.  -0.5]]
